export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const SEND_OTP_BEGIN = "SEND_OTP_BEGIN";
export const SEND_OTP_ERROR = "SEND_OTP_ERROR";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";

export const LOGIN_BEGIN = "LOGIN_BEGhyysdyxbIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_ALL_ACCOUNTS_BEGIN = "GET_ALL_ACCOUNTS_BEGIN";
export const GET_ALL_ACCOUNTS_SUCCESS = "GET_ALL_ACCOUNTS_SUCCESS";

export const ADD_ACCOUNT_BEGIN = "ADD_ACCOUNT_BEGIN";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_ERROR = "ADD_ACCOUNT_ERROR";

export const EDIT_ACCOUNT_BEGIN = "EDIT_ACCOUNT_BEGIN";
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";
export const EDIT_ACCOUNT_ERROR = "EDIT_ACCOUNT_ERROR";

export const DELETE_ACCOUNT_BEGIN = "DELETE_ACCOUNT_BEGIN";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";

export const UPDATE_PROFILE_BEGIN = "UPDATE_PROFILE_BEGIN";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const GET_ROOMS_BEGIN = "GET_ROOMS_INFO_BEGIN";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_ERROR";
export const GET_ROOMS_ERROR = "GET_ROOMS_INFO_ERRO";

export const REQUEST_ROOM_BEGIN = "REQUEST_ROOM_BEGIN";
export const REQUEST_ROOM_SUCCESS = "REQUEST_ROOM_SUCCESS";
export const REQUEST_ROOM_ERROR = "REQUEST_ROOM_ERROR";

export const GET_CLUBS_BEGIN = "GET_CLUBS_DATA_BEGIN";
export const GET_CLUBS_SUCCESS = "GET_CLUBS_SUCCESS";
export const GET_CLUBS_ERROR = "GET_CLUBS_ERROR";

export const UPDATE_REQUEST_BEGIN = "UPDATE_REQUEST_BEGIN";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_ERROR = "UPDATE_REQUEST_ERROR";
